
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Roberto
 */
public class Explorador extends javax.swing.JInternalFrame {

    File[] archivosIniciales;
    String ventanaTitulo;
    ImageIcon ventanaIcono;
    FileSystemView fsv = FileSystemView.getFileSystemView();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");

    /**
     * Creates new form MiEquipo
     */
    public Explorador() {
        this.archivosIniciales = new File[]{};
        this.ventanaTitulo = "";
        this.ventanaIcono = null;
        initComponents();
    }

    public Explorador(File[] archivosIniciales, String ventanaTitulo, ImageIcon ventanaIcono) {
        this.archivosIniciales = archivosIniciales;
        this.ventanaTitulo = ventanaTitulo;
        this.ventanaIcono = ventanaIcono;
        initComponents();

        ponerArchivosIniciales();
    }

    private void ponerArchivosIniciales() {
        DefaultTableModel dtm = (DefaultTableModel) tablaArchivos.getModel();

        for (int i = 0; i < archivosIniciales.length; i++) {
            Vector v = new Vector();
            //v.add((Icon) fsv.getSystemIcon(roots[i]));
            v.add(fsv.getSystemDisplayName(archivosIniciales[i]));
            v.add(sdf.format(archivosIniciales[i].lastModified()));
            v.add(fsv.getSystemTypeDescription(archivosIniciales[i]));
            v.add(archivosIniciales[i].getTotalSpace() / (1024 * 1024 * 1024) + " GB");

            dtm.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        panelTabla = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        panelArbol = new javax.swing.JScrollPane();
        arbolArchivos = new javax.swing.JTree();
        campoRuta = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(ventanaTitulo);
        setFrameIcon(ventanaIcono);

        jDesktopPane2.setBackground(new java.awt.Color(153, 255, 204));

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha de modificacion", "Tipo", "Tamaño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaArchivos.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tablaArchivos.setRowHeight(20);
        tablaArchivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaArchivos.setShowHorizontalLines(false);
        tablaArchivos.setShowVerticalLines(false);
        tablaArchivos.getTableHeader().setResizingAllowed(false);
        tablaArchivos.getTableHeader().setReorderingAllowed(false);
        panelTabla.setViewportView(tablaArchivos);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDesktopPane2.setLayer(panelTabla, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(204, 255, 204));

        panelArbol.setViewportView(arbolArchivos);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArbol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        jDesktopPane3.setLayer(panelArbol, javax.swing.JLayeredPane.DEFAULT_LAYER);

        campoRuta.setText("Equipo");
        campoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2))
            .addComponent(campoRuta)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(campoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2)
                    .addComponent(jDesktopPane3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRutaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolArchivos;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JScrollPane panelArbol;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JTable tablaArchivos;
    // End of variables declaration//GEN-END:variables
}
